require('dotenv').config();
const mongoose = require('mongoose');
const Job = require('./models/Job');

const jobs = [
  {
    title: 'Email Marketing',
    company: 'Revolut',
    companyLogo: 'R',
    location: 'Madrid, Spain',
    category: 'Marketing',
    type: 'Full Time',
    description: 'Revolut is looking for Email Marketing to help team member manage email campaigns, analyze performance, and drive customer engagement. You will work with a talented team to create impactful email strategies.',
    requirements: 'Experience with email marketing platforms, strong analytical skills, knowledge of A/B testing, familiarity with HTML/CSS for email templates.',
    salary: '$60,000 - $80,000',
    tags: ['Marketing', 'Design'],
    featured: true,
  },
  {
    title: 'Brand Designer',
    company: 'Dropbox',
    companyLogo: 'D',
    location: 'San Francisco, US',
    category: 'Design',
    type: 'Full Time',
    description: 'Dropbox is looking for Brand Designer to help the team create compelling visual identities and brand experiences. You will collaborate with product and marketing teams.',
    requirements: 'Strong portfolio in brand design, proficiency in Figma and Adobe Suite, experience with design systems.',
    salary: '$90,000 - $120,000',
    tags: ['Design', 'Business'],
    featured: true,
  },
  {
    title: 'Email Marketing',
    company: 'Pitch',
    companyLogo: 'P',
    location: 'Berlin, Germany',
    category: 'Marketing',
    type: 'Full Time',
    description: 'Pitch is looking for Customer Manager to join marketing team and develop innovative email campaigns that resonate with our growing user base.',
    requirements: 'Proven track record in email marketing, experience with CRM tools, data-driven mindset.',
    salary: '€55,000 - €75,000',
    tags: ['Marketing'],
    featured: true,
  },
  {
    title: 'Visual Designer',
    company: 'Blinkist',
    companyLogo: 'B',
    location: 'Granada, Spain',
    category: 'Design',
    type: 'Full Time',
    description: 'Blinkist is looking for Visual Designer to help team deal with UI/UX challenges across the product and marketing channels.',
    requirements: 'Experience in visual design, strong UI/UX skills, portfolio showcasing diverse design projects.',
    salary: '€50,000 - €70,000',
    tags: ['Design'],
    featured: true,
  },
  {
    title: 'Product Designer',
    company: 'ClassPass',
    companyLogo: 'C',
    location: 'Manchester, UK',
    category: 'Design',
    type: 'Full Time',
    description: 'ClassPass is looking for Product Designer to help us create beautiful, intuitive interfaces for millions of fitness enthusiasts worldwide.',
    requirements: 'Strong product design portfolio, experience with user research, proficiency in Figma.',
    salary: '£55,000 - £75,000',
    tags: ['Marketing', 'Design'],
    featured: true,
  },
  {
    title: 'Lead Engineer',
    company: 'Canva',
    companyLogo: 'C',
    location: 'Ontario, Canada',
    category: 'Engineering',
    type: 'Full Time',
    description: 'Canva is looking for Lead Engineer to help Anmol n build scalable systems and mentor a team of talented engineers.',
    requirements: 'Strong software engineering background, experience leading teams, proficiency in modern web technologies.',
    salary: 'CAD $130,000 - $160,000',
    tags: ['Design', 'Business'],
    featured: true,
  },
  {
    title: 'Brand Strategist',
    company: 'GoDaddy',
    companyLogo: 'G',
    location: 'Marseille, France',
    category: 'Marketing',
    type: 'Full Time',
    description: 'GoDaddy is looking for Brand Strategist to join the team and develop comprehensive brand strategies that drive business growth.',
    requirements: 'Experience in brand strategy, strong analytical and creative skills, ability to work cross-functionally.',
    salary: '€65,000 - €85,000',
    tags: ['Marketing'],
    featured: true,
  },
  {
    title: 'Data Analyst',
    company: 'Twitter',
    companyLogo: 'T',
    location: 'San Diego, US',
    category: 'Technology',
    type: 'Full Time',
    description: 'Twitter is looking for Data Analyst to help team docs and drive data-driven decisions across the organization.',
    requirements: 'Proficiency in SQL, Python, or R, experience with data visualization tools, strong statistical knowledge.',
    salary: '$95,000 - $125,000',
    tags: ['Technology'],
    featured: true,
  },
  {
    title: 'Social Media Assistant',
    company: 'Nomad',
    companyLogo: 'N',
    location: 'Paris, France',
    category: 'Marketing',
    type: 'Full Time',
    description: 'Join Nomad\'s creative team and help manage social media channels to grow our community and brand presence across all platforms.',
    requirements: 'Experience with social media management, strong content creation skills, knowledge of analytics tools.',
    salary: '€40,000 - €55,000',
    tags: ['Marketing', 'Design'],
    featured: false,
  },
  {
    title: 'Brand Designer',
    company: 'Dropbox',
    companyLogo: 'D',
    location: 'San Francisco, USA',
    category: 'Design',
    type: 'Full Time',
    description: 'Another opportunity with Dropbox for experienced brand designers to work on exciting new product lines.',
    requirements: 'Strong portfolio, expert in Figma and Adobe tools, experience in tech industry branding.',
    salary: '$85,000 - $110,000',
    tags: ['Marketing', 'Design'],
    featured: false,
  },
  {
    title: 'Interactive Developer',
    company: 'Terraform',
    companyLogo: 'T',
    location: 'Hamburg, Germany',
    category: 'Technology',
    type: 'Full Time',
    description: 'Build cutting-edge interactive experiences with Terraform. You will work on creative tech projects using the latest web technologies.',
    requirements: 'Experience with WebGL, Three.js, creative coding, strong JavaScript skills.',
    salary: '€70,000 - €95,000',
    tags: ['Marketing', 'Design'],
    featured: false,
  },
  {
    title: 'HR Manager',
    company: 'Packer',
    companyLogo: 'P',
    location: 'Lucern, Switzerland',
    category: 'Human Resources',
    type: 'Full Time',
    description: 'Lead human resources initiatives at Packer, fostering a positive work culture and managing talent acquisition strategies.',
    requirements: 'HR certification, experience in recruitment and employee relations, knowledge of Swiss labor law.',
    salary: 'CHF 90,000 - 120,000',
    tags: ['Marketing', 'Design'],
    featured: false,
  },
  {
    title: 'Social Media Assistant',
    company: 'Netlify',
    companyLogo: 'N',
    location: 'Paris, France',
    category: 'Marketing',
    type: 'Full Time',
    description: 'Help Netlify grow its developer community through engaging social media content and community management.',
    requirements: 'Understanding of developer tools/platforms, social media expertise, strong writing skills.',
    salary: '€42,000 - €58,000',
    tags: ['Marketing', 'Design'],
    featured: false,
  },
  {
    title: 'Brand Designer',
    company: 'Maze',
    companyLogo: 'M',
    location: 'San Francisco, USA',
    category: 'Design',
    type: 'Full Time',
    description: 'Shape the visual identity of Maze, a rapidly growing product research platform used by top design teams globally.',
    requirements: 'Strong brand design portfolio, experience in SaaS companies, proficiency in modern design tools.',
    salary: '$80,000 - $105,000',
    tags: ['Marketing', 'Design'],
    featured: false,
  },
  {
    title: 'Interactive Developer',
    company: 'Udacity',
    companyLogo: 'U',
    location: 'Hamburg, Germany',
    category: 'Technology',
    type: 'Full Time',
    description: 'Create immersive learning experiences at Udacity. Build interactive course content that helps students master new skills.',
    requirements: 'Experience in educational technology, strong frontend skills, passion for learning platforms.',
    salary: '€65,000 - €90,000',
    tags: ['Marketing', 'Design'],
    featured: false,
  },
  {
    title: 'HR Manager',
    company: 'Webflow',
    companyLogo: 'W',
    location: 'Lucern, Switzerland',
    category: 'Human Resources',
    type: 'Full Time',
    description: 'Build and scale Webflow\'s people operations as we continue our rapid growth phase in the European market.',
    requirements: 'People operations experience, talent acquisition skills, ability to work in fast-paced startup environment.',
    salary: 'CHF 85,000 - 115,000',
    tags: ['Marketing', 'Design'],
    featured: false,
  },
  {
    title: 'UX Researcher',
    company: 'Figma',
    companyLogo: 'F',
    location: 'Remote',
    category: 'Design',
    type: 'Remote',
    description: 'Help Figma understand its users better through comprehensive research studies, usability testing, and data analysis.',
    requirements: 'Experience in UX research methodologies, strong analytical skills, ability to translate research into actionable insights.',
    salary: '$100,000 - $140,000',
    tags: ['Design', 'Technology'],
    featured: false,
  },
  {
    title: 'Sales Manager',
    company: 'HubSpot',
    companyLogo: 'H',
    location: 'Dublin, Ireland',
    category: 'Sales',
    type: 'Full Time',
    description: 'Lead a high-performing sales team at HubSpot. Drive revenue growth and develop sales strategies for the European market.',
    requirements: 'Proven sales leadership experience, knowledge of CRM software, strong communication and negotiation skills.',
    salary: '€80,000 - €110,000 + commission',
    tags: ['Sales', 'Business'],
    featured: false,
  },
  {
    title: 'Financial Analyst',
    company: 'Stripe',
    companyLogo: 'S',
    location: 'Dublin, Ireland',
    category: 'Finance',
    type: 'Full Time',
    description: 'Join Stripe\'s finance team to analyze financial data, build models, and provide insights that guide strategic business decisions.',
    requirements: 'Strong financial modeling skills, experience with data analysis, CPA or CFA preferred.',
    salary: '€75,000 - $100,000',
    tags: ['Finance', 'Business'],
    featured: false,
  },
  {
    title: 'Business Development Manager',
    company: 'Notion',
    companyLogo: 'N',
    location: 'Tokyo, Japan',
    category: 'Business',
    type: 'Full Time',
    description: 'Drive Notion\'s expansion in the Asia Pacific region by developing strategic partnerships and identifying new market opportunities.',
    requirements: 'Business development experience in APAC, strong network, bilingual (English/Japanese preferred).',
    salary: '¥8,000,000 - ¥12,000,000',
    tags: ['Business', 'Sales'],
    featured: false,
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/quickhire');
    console.log('✅ Connected to MongoDB');

    await Job.deleteMany({});
    console.log('🗑️  Cleared existing jobs');

    const created = await Job.insertMany(jobs);
    console.log(`✅ Seeded ${created.length} jobs`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error.message);
    process.exit(1);
  }
};

seed();
